name: Build and Push Docker Image

# Настройка запуска для обеих веток (main и develop)
on:
  push:
    branches: [ "main", "develop" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./lab2
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/my-flask-app:latest

    # Условный деплой для ветки main
    - name: Deploy to Production
      if: github.ref == 'refs/heads/main'
      run: echo "Deploying to production server..."

    # Условный деплой для ветки develop
    - name: Deploy to Development
      if: github.ref == 'refs/heads/develop'
      run: echo "Deploying to development server..."
